---
- name: creating container by pulling the image from amazon ecr
  hosts: webservers
  tasks:
   - name: removing old containers
     shell: docker container rm -f $(docker container ls -a -q)
   - name: removing all old images
     shell: docker image rm -f $(docker image ls -a -q)
   - name: creating container 
     shell: docker container run -d -p 8070:80 --name sasireddy 302600509576.dkr.ecr.us-east-2.amazonaws.com/sasireddy
